import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class BWriter {
	
	public static void main(String[] args) throws IOException {
		FileWriter fw=new FileWriter("D://file2.html");
		BufferedWriter bwriter=new BufferedWriter(fw);
		String constant="<html><head><title>THIS FILE IS GENERATED BY CODE</title></head><body>this is the first file by paras</body></html>";
		char [] arr=constant.toCharArray();
		for(char c: arr){
			bwriter.write(c);
		}
		
		bwriter.flush();
		bwriter.close();
	}

}
