name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
        Enter Branch:
          description: Enter branch name
          required: false
          type: boolean
          default: false
        Build_Business:
          description: Enter markets
          required: false
          type: String
          default: "In Sea Ph Mea"
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
