name: Check PR for new tests

on:
  pull_request:
    branches:
      - master

jobs:
  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for new tests
        run: |
          baseDate="2023-03-27"
          today=$(date -u +%s)
          start=$(date -u -d "$baseDate" +%s)
          echo today >> $GITHUB_OUTPUT
          echo start >> $GITHUB_OUTPUT
          




