name: Check PR for new tests

on:
  pull_request:
    branches:
      - master

jobs:
  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check for new tests
        run: |
           git diff --name-only origin/master...$GITHUB_HEAD_REF | grep "androidTest"
