name: Check PR for new tests

on:
  pull_request:
    branches:
      - master

jobs:
  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Check for new tests
        run: 
          git checkout $GITHUB_HEAD_REF
          if git diff master...$GITHUB_HEAD_REF | grep "androidTest"; then
            echo "New test files added to androidTest folder"
            exit 1
          fi

          if git diff --name-only master..$GITHUB_HEAD_REF | xargs grep -q "@Test"; then
            echo "New test methods added to existing files in androidTest folder"
            exit 1
          fi




