name: Check PR for new tests

on:
  workflow_dispatch

jobs:
  check_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for new tests
        run: |
          baseDate="2023-03-27"
          today=$(date -u +%s)
          start=$(date -u -d "$baseDate" +%s)
          echo $today
          echo $start
