name: first
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
    inputs:
      Enter_Branch:
        description: Enter branch name
        required: false
        type: String
        default: false
      Build_Business:
        description: Enter markets
        required: false
        type: String
        default: "In Sea Ph Mea"
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    outputs:
      BRANCH: ${{steps.branch.outputs.BRANCHNAME}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Initialize Mandatory Git Config
        run: echo "HI"
      - name: Creating branch
        run: git checkout -b ${{inputs.Enter_Branch}}
      - name: Push new branch
        run: git push origin ${{inputs.Enter_Branch}}
      - name: Getting Branch Name
        id: branch
        run: echo "BRANCHNAME=release-`date +%y-%m-%d`" >> $GITHUB_OUTPUT
      - name: Output Github
        run: echo $GITHUB_OUTPUT   
