name: Create Release
on:
  workflow_dispatch:
    inputs:
      Enter Branch:
        description: Enter branch name
        required: false
        type: boolean
        default: false
      Build_Business:
        description: Enter markets
        required: false
        type: String
        default: "In Sea Ph Mea"

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
    - name: echo print
    - run: echo $${github.actor}}
